### ISSUE TITLE
Literally unplayable

### ISSUE THREAD

**Issue by C1bergh0st** [pbrinkmeier/tichy-clicker#18]
resources/shops.json describes "Maven installieren" as increasing Commits/s by 2 while it actually increases Commits/s by 0.2

please fix

**Comment by C1bergh0st** [comment]
coverage is also wrong

**Comment by pbrinkmeier** [comment]
The intent is to provide players with a sense of pride and accomplishment for unlocking different skills.

As for cost, we selected initial values based upon data from the Open Beta and other adjustments made to milestone rewards before launch. Among other things, we're looking at average per-player credit earn rates on a daily basis, and we'll be making constant adjustments to ensure that players have challenges that are compelling, rewarding, and of course attainable via gameplay.

We appreciate the candid feedback, and the passion the community has put forth around the current topics here on GitHub, our forums and across numerous social media outlets.

Our team will continue to make changes and monitor community feedback and update everyone as soon and as often as we can.

**Comment by C1bergh0st** [comment]
5/7 response

**Comment by pbrinkmeier** [comment]
Solved. You may need to invalidate your cache tho.
