### ISSUE TITLE
Problems when local storage is >5mb

### ISSUE THREAD

**Issue by BLuedtke** [pbrinkmeier/tichy-clicker#24]
Data is currently being saved to local storage. Some browsers have a hard cap (5MB) on local storage. If the quota is reached (for me at 126.000.462.954 Commits and A LOT of mouse clicks), the site/appl. seizes to function.

**Comment by pbrinkmeier** [comment]
The number of commits shouldn't really be a problem. The problem is that the state of all the particles is saved to the local storage.

One could argue that the particles *really* don't need to be saved along with the game state. It shouldn't be a lot of work to avoid that.
