### ISSUE TITLE
not enough ingame purchases

### ISSUE THREAD

**Issue by t1ch1** [pbrinkmeier/tichy-clicker#25]
please add:
- tichy-skins (suits, hats, backgrounds)
- tichy-lootboxes (with skins, bonus commits and different rarity)
- reputation system with resetting the progress by earning git repos for boosting the new attempt (also with übungsscheinen and Klausuren as higher level rewards)

**Comment by pbrinkmeier** [comment]
If you're up to create some content, I'll be happy to add it to the game. I haven't been in a Tichy lecture for a while now, so I'm all out of ideas :(
