### ISSUE TITLE
Show gain in shops

### ISSUE THREAD

**Issue by seyfahni** [pbrinkmeier/tichy-clicker#26]
While in shops, it would be nice to be able to see how much per second / per click will be gained. This would make it easier to select which upgrades to buy after collecting a great amount of commits and being able to buy multiple upgrades at once.

**Comment by pbrinkmeier** [comment]
I could add that to the number of commits in the upper right region of the shop screen, is that what you  mean?

**Comment by pbrinkmeier** [comment]
I could add that to the number of commits in the upper right region of the shop screen, is that what you  mean?

**Comment by seyfahni** [comment]
Yeah, for example.
