### ISSUE TITLE
New skills/systems

### ISSUE THREAD

**Issue by pbrinkmeier** [pbrinkmeier/tichy-clicker#8]
Comment with ideas for new skills or systems

**Comment by pbrinkmeier** [comment]
- Use Maven without crying -> Skills
- Build Fancy GUI -> Systems

**Comment by seyfahni** [comment]
I've rendered the Tichy image using my Geometrify with 10.000 iterations and 1.000 samples about 6.5 hours long.
How about a geometrify-related skill / system that changes the Tichy picture?
~[Geometrified 10000 1000](https://seyfahni.de/files/geometrify/2017-06-21_08-10-25_511_geometrifiedPicture.png)~ (link dead)
There is also an edited version (I've just used gimps remove stains):
~[Geometrified 10000 1000 (edited)](https://seyfahni.de/files/geometrify/2017-06-21_08-10-25_511_geometrifiedPicture_edited.png)~ (link dead)

**Comment by pbrinkmeier** [comment]
Great idea!

I've been thinking about a new "feature" called power-ups for a while now. Power-ups would give you big bonuses for a certain time (say every click is counted twice for 30 sec) and screw with the GUI. Maybe we could add a power-up where tichy gets more and more geometrified (starting at something like 100 iterations and going up to your 10000). But we would need some more frames (which would introduce a lot of pageload) or an implementation in javascript, which is likely to be far less performant than the java implementation. Anyways, could you generate some more frames, about 10, logarithmically between 100 and 10000 iterations? Then I could use them for the power-up

**Comment by pbrinkmeier** [comment]
Another idea for the geometrify power-up: triangle falling down in the background

**Comment by seyfahni** [comment]
Ok, rendering is complete. The [zip](http://seyfahni.de/files/geometrify/geometrify.zip) contains 12 images, everyone with 1000 samples, iterations: 100, 158, 251, 398, 631, 1000, 1585, 2512, 3981, 6310, 10000. The formula I used for number of iterations is 10^(2+r) ; r element {0, 0.2, …, 1.8, 2}. Both pictures linked above are also included.

**Comment by pbrinkmeier** [comment]
Sweet, thanks! I build the power ups in the next few days :)

**Comment by pbrinkmeier** [comment]
Sorry that this is taking so long, got a lot of things on my mind right now. Didn't forget about this tho.

**Comment by pbrinkmeier** [comment]
- Make iMage cost more, give less (other new systems too)
- New skills (PSE-Betreuer?)

**Comment by pbrinkmeier** [comment]
- Gedrängemeister
- SWT1-Tutor werden
- Brandmauersystem

**Comment by seyfahni** [comment]
Although I have no idea how to use it as a skill or system, "Stöberer" (Browser) might fit quite well.
